description: In this workshop we'll start from the very foundation of what makes React such a useful and transformational abstraction in modern website development. From this foundational perspective we'll explain the ins and outs of React ranging from JSX (why is this HTML in my JS!?), props, functional components, local component state, and everything in between to empower you to begin building incredible applications with React.
keywords:
  - react
  - redux
  - workshop
  - javascript
title: React Training
